// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VolSurf.Data;

#nullable disable

namespace VolSurf.Data.Migrations
{
    [DbContext(typeof(VolSurfDbContext))]
    partial class VolSurfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VolSurf.Data.Entities.IvGreeks", b =>
                {
                    b.Property<string>("TsCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Delta")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("Gamma")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("Iv")
                        .HasColumnType("decimal(8,4)");

                    b.Property<bool>("IvAnomaly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IvConfidence")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Rho")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("Theta")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Vega")
                        .HasColumnType("decimal(8,4)");

                    b.HasKey("TsCode", "TradeDate");

                    b.HasIndex("TradeDate", "Underlying");

                    b.HasIndex("Underlying", "TradeDate");

                    b.ToTable("options_iv_greeks", (string)null);
                });

            modelBuilder.Entity("VolSurf.Data.Entities.IvPercentileCache", b =>
                {
                    b.Property<string>("Underlying")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("AtmIv")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("IvMean")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal?>("IvPercentile")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("IvStd")
                        .HasColumnType("decimal(8,4)");

                    b.Property<int?>("SampleDays")
                        .HasColumnType("integer");

                    b.HasKey("Underlying", "TradeDate");

                    b.ToTable("iv_percentile_cache", (string)null);
                });

            modelBuilder.Entity("VolSurf.Data.Entities.OptionContract", b =>
                {
                    b.Property<string>("TsCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("Adjusted")
                        .HasColumnType("boolean");

                    b.Property<string>("CallPut")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("DelistDate")
                        .HasColumnType("date");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("ExercisePrice")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("ListDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("OptMultiplier")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("TsCode");

                    b.HasIndex("MaturityDate");

                    b.HasIndex("Underlying");

                    b.ToTable("options_contracts", (string)null);
                });

            modelBuilder.Entity("VolSurf.Data.Entities.OptionDaily", b =>
                {
                    b.Property<string>("TsCode")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(15,4)");

                    b.Property<decimal?>("Close")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("High")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("Low")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("Oi")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("Open")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("Settle")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Underlying")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Vol")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("TsCode", "TradeDate");

                    b.HasIndex("TradeDate");

                    b.HasIndex("TsCode", "TradeDate");

                    b.HasIndex("Underlying", "TradeDate");

                    b.ToTable("options_daily", (string)null);
                });

            modelBuilder.Entity("VolSurf.Data.Entities.Underlying", b =>
                {
                    b.Property<string>("TsCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("TsCode");

                    b.ToTable("underlyings", (string)null);
                });

            modelBuilder.Entity("VolSurf.Data.Entities.UnderlyingDaily", b =>
                {
                    b.Property<string>("TsCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("TsCode", "TradeDate");

                    b.ToTable("underlying_daily", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
